/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import mydatabase.Database;

/**
 *
 * @author nikolaos
 */
public class DeleteDatabaseJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ShowDatabasesJDialog
     */
    public DeleteDatabaseJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listOfDbsJLabel = new javax.swing.JLabel();
        databasesJComboBox = new javax.swing.JComboBox<>();
        cancelJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listOfDbsJLabel.setText("List of Existing Databases to Choose from");

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setText("Delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(listOfDbsJLabel)
                        .addComponent(databasesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listOfDbsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(databasesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton)
                    .addComponent(deleteJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Database db = new Database();
        List<String> dbList = db.fetchDatabasesGUI();
        for (String dbName : dbList) {
            this.databasesJComboBox.addItem(dbName);
        }
    }//GEN-LAST:event_formWindowOpened

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        String dbName = (String) this.databasesJComboBox.getSelectedItem();
        int inputValue = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete database " + dbName,
                "Warning!",
                JOptionPane.YES_NO_OPTION);
        if (inputValue == 0) { //YES
            MainFrame mainFrm = (MainFrame) this.getParent();
            Database db = new Database();
            if (db.deleteDatabaseGUI(dbName)) {
                JOptionPane.showMessageDialog(this, "Succesfully deleted database with name " + dbName + " !");
            } else {
                JOptionPane.showMessageDialog(this, "Could not delete database with name " + dbName + "...",
                        "Other I/O error",
                        JOptionPane.ERROR_MESSAGE);
            }
            JScrollPane jScrollPane = mainFrm.getDbObjectsTreeJScrollPane();
            jScrollPane.setViewportView(null);
            JTabbedPane jTabbedPane = mainFrm.getDbDetailsJTabbedPane();
            if (jTabbedPane.isVisible()) {
                jTabbedPane.setVisible(false);
            }
            JSplitPane jSplitPane = mainFrm.getMainJSplitPane();
            jSplitPane.setDividerLocation(0);
        }
        this.dispose();
    }//GEN-LAST:event_deleteJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JComboBox<String> databasesJComboBox;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JLabel listOfDbsJLabel;
    // End of variables declaration//GEN-END:variables
}
