/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author nikolaos
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public JScrollPane getDbObjectsTreeJScrollPane() {
        return dbObjectsTreeJScrollPane;
    }

    public void setDbObjectsTreeJScrollPane(JScrollPane dbObjectsTreeJScrollPane) {
        this.dbObjectsTreeJScrollPane = dbObjectsTreeJScrollPane;
    }

    public JSplitPane getMainJSplitPane() {
        return mainJSplitPane;
    }

    public void setMainJSplitPane(JSplitPane mainJSplitPane) {
        this.mainJSplitPane = mainJSplitPane;
    }

    public JTabbedPane getDbDetailsJTabbedPane() {
        return dbDetailsJTabbedPane;
    }

    public void setDbDetailsJTabbedPane(JTabbedPane dbDetailsJTabbedPane) {
        this.dbDetailsJTabbedPane = dbDetailsJTabbedPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJSplitPane = new javax.swing.JSplitPane();
        databaseJPanel = new javax.swing.JPanel();
        dbObjectsTreeJScrollPane = new javax.swing.JScrollPane();
        dbDetailsJTabbedPane = new javax.swing.JTabbedPane();
        mainMenuBar = new javax.swing.JMenuBar();
        mainJMenu = new javax.swing.JMenu();
        createDatabaseJMenuItem = new javax.swing.JMenuItem();
        editJMenuItem = new javax.swing.JMenuItem();
        deleteJMenuItem = new javax.swing.JMenuItem();
        maintainJMenuItem = new javax.swing.JMenuItem();
        exitJMenuItem = new javax.swing.JMenuItem();
        aboutJMenu = new javax.swing.JMenu();
        ourTeamJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Database");
        setPreferredSize(new java.awt.Dimension(1000, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainJSplitPane.setDividerLocation(100);

        databaseJPanel.setLayout(new java.awt.BorderLayout());
        databaseJPanel.add(dbObjectsTreeJScrollPane, java.awt.BorderLayout.CENTER);

        mainJSplitPane.setLeftComponent(databaseJPanel);
        mainJSplitPane.setRightComponent(dbDetailsJTabbedPane);

        getContentPane().add(mainJSplitPane, java.awt.BorderLayout.CENTER);

        mainJMenu.setText("Database");

        createDatabaseJMenuItem.setText("Create");
        createDatabaseJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDatabaseJMenuItemActionPerformed(evt);
            }
        });
        mainJMenu.add(createDatabaseJMenuItem);

        editJMenuItem.setText("Edit");
        editJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJMenuItemActionPerformed(evt);
            }
        });
        mainJMenu.add(editJMenuItem);

        deleteJMenuItem.setText("Delete");
        deleteJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJMenuItemActionPerformed(evt);
            }
        });
        mainJMenu.add(deleteJMenuItem);

        maintainJMenuItem.setText("Maintain");
        maintainJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainJMenuItemActionPerformed(evt);
            }
        });
        mainJMenu.add(maintainJMenuItem);

        exitJMenuItem.setText("Exit");
        exitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJMenuItemActionPerformed(evt);
            }
        });
        mainJMenu.add(exitJMenuItem);

        mainMenuBar.add(mainJMenu);

        aboutJMenu.setText("About");

        ourTeamJMenuItem.setText("Our Team");
        ourTeamJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourTeamJMenuItemActionPerformed(evt);
            }
        });
        aboutJMenu.add(ourTeamJMenuItem);

        mainMenuBar.add(aboutJMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJMenuItemActionPerformed
        // TODO add your handling code here:
        DeleteDatabaseJDialog deleteDatabaseJDialog = new DeleteDatabaseJDialog(this, true);
        deleteDatabaseJDialog.setLocationRelativeTo(this);
        deleteDatabaseJDialog.setVisible(true);
    }//GEN-LAST:event_deleteJMenuItemActionPerformed

    private void ourTeamJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourTeamJMenuItemActionPerformed
        // TODO add your handling code here:
        AboutJDialog aboutJDialog = new AboutJDialog(this, true);
        aboutJDialog.setLocationRelativeTo(this);
        aboutJDialog.setVisible(true);
    }//GEN-LAST:event_ourTeamJMenuItemActionPerformed

    private void exitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitJMenuItemActionPerformed

    private void createDatabaseJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDatabaseJMenuItemActionPerformed
        // TODO add your handling code here:
        CreateDatabaseJDialog createDatabaseJDialog = new CreateDatabaseJDialog(this, true);
        createDatabaseJDialog.setLocationRelativeTo(this);
        createDatabaseJDialog.setVisible(true);
    }//GEN-LAST:event_createDatabaseJMenuItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.mainJSplitPane.setDividerLocation(0);
    }//GEN-LAST:event_formWindowOpened

    private void editJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJMenuItemActionPerformed
        // TODO add your handling code here:
        ShowDatabasesJDialog showDatabasesJDialog = new ShowDatabasesJDialog(this, true);
        showDatabasesJDialog.setLocationRelativeTo(this);
        showDatabasesJDialog.setVisible(true);
    }//GEN-LAST:event_editJMenuItemActionPerformed

    private void maintainJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainJMenuItemActionPerformed
        // TODO add your handling code here:
        MaintainDatabaseJDialog maintainDatabaseJDialog = new MaintainDatabaseJDialog(this, true);
        maintainDatabaseJDialog.setLocationRelativeTo(this);
        maintainDatabaseJDialog.setVisible(true);
    }//GEN-LAST:event_maintainJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutJMenu;
    private javax.swing.JMenuItem createDatabaseJMenuItem;
    private javax.swing.JPanel databaseJPanel;
    private javax.swing.JTabbedPane dbDetailsJTabbedPane;
    private javax.swing.JScrollPane dbObjectsTreeJScrollPane;
    private javax.swing.JMenuItem deleteJMenuItem;
    private javax.swing.JMenuItem editJMenuItem;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JMenu mainJMenu;
    private javax.swing.JSplitPane mainJSplitPane;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem maintainJMenuItem;
    private javax.swing.JMenuItem ourTeamJMenuItem;
    // End of variables declaration//GEN-END:variables
}
