/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import mydatabase.Database;

/**
 *
 * @author nikolaos
 */
public class MaintainDatabaseJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ShowDatabasesJDialog
     */
    public MaintainDatabaseJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listOfDbsJLabel = new javax.swing.JLabel();
        databasesJComboBox = new javax.swing.JComboBox<>();
        cancelJButton = new javax.swing.JButton();
        maintainJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listOfDbsJLabel.setText("List of Existing Databases to Choose from");

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        maintainJButton.setText("Maintain");
        maintainJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maintainJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(listOfDbsJLabel)
                        .addComponent(databasesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listOfDbsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(databasesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton)
                    .addComponent(maintainJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Database db = new Database();
        List<String> dbList = db.fetchDatabasesGUI();
        for (String dbName : dbList) {
            this.databasesJComboBox.addItem(dbName);
        }
    }//GEN-LAST:event_formWindowOpened

    private void maintainJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainJButtonActionPerformed
        // TODO add your handling code here:
        String dbName = (String) this.databasesJComboBox.getSelectedItem();
        MainFrame mainFrm = (MainFrame) this.getParent();
        Database db = new Database();
        if (db.maintainDatabaseGUI(dbName)) {
            JOptionPane.showMessageDialog(this, "Succesfully maintained database with name " + dbName + " !");
        } else {
            JOptionPane.showMessageDialog(this, "Could not maintain database with name " + dbName + "...",
                    "Other I/O error",
                    JOptionPane.ERROR_MESSAGE);
        }
        JScrollPane jScrollPane = mainFrm.getDbObjectsTreeJScrollPane();
        jScrollPane.setViewportView(null);
        JTabbedPane jTabbedPane = mainFrm.getDbDetailsJTabbedPane();
        if(jTabbedPane.isVisible()){
            jTabbedPane.removeAll();
            jTabbedPane.setVisible(false);
        }  
        JSplitPane jSplitPane = mainFrm.getMainJSplitPane();
        jSplitPane.setDividerLocation(0);

        this.dispose();
    }//GEN-LAST:event_maintainJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JComboBox<String> databasesJComboBox;
    private javax.swing.JLabel listOfDbsJLabel;
    private javax.swing.JButton maintainJButton;
    // End of variables declaration//GEN-END:variables
}
